apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gateway
    spec:
      containers:
        - image: spring-6-gateway:0.0.1-SNAPSHOT
          name: spring-6-gateway
          resources: {}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_SECURITY_AOUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://auth-server:9000
status: {}
