apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo
    spec:
      containers:
        - image: mongo
          name: mongo
          resources: {}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: sebastian
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "zirael#43#"
status: {}
