apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8
          name: mysql
          resources: {}
          env:
            - name: MYSQL_USER
              value: restadmin
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: restdb
            - name: MYSQL_ROOT_PASSWORD
              value: password
status: {}
