apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: reactive-mongo
  name: reactive-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactive-mongo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reactive-mongo
    spec:
      containers:
        - image: spring-6-reactive-mongo:0.0.1-SNAPSHOT
          name: spring-6-reactive-mongo
          resources: {}
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://auth-server:9000
            - name: SFG_MONGOHOST
              value: mongo
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://sebastian:zirael%2343%23@mongo:27017/reactive_mongo?authSource=admin
status: {}
